#!/bin/bash
#######################################################
# Run app helper. Ensure GOPATH/bin is in your PATH.
#######################################################

APPNAME=app
ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
APPDIR=$ROOTDIR/cmd/$APPNAME

cd $APPDIR

case "$1" in
dev)
  echo "Starting hot reload..."
  go get github.com/githubnemo/CompileDaemon
  CompileDaemon -log-prefix=false -color=true -build="$ROOTDIR/run dev-build-and-sign" -command="./app"
  ;;
build)
  echo "Building app..."
  go build -o app
  ;;
test)
  echo "Test not yet implemented"
  ;;
dev-build-and-sign)
  go build -o app
  #codesign -f --deep -s apps $APPDIR/app
  ;;
docker)
  echo "Building docker..."
  DOCKER_BUILDKIT=1 docker build --ssh default -t app $ROOTDIR
  echo "Running docker..."
  docker run --env-file $ROOTDIR/.env -P --rm -p 3000:3000 app
  ;;
dev-docker)
  echo "Starting hot reload using docker..."
  go get github.com/githubnemo/CompileDaemon
  CompileDaemon -log-prefix=false -color=true -build="$ROOTDIR/run dev-docker-build" -command="docker run --env-file $ROOTDIR/.env -P --rm -p 3000:3000 app" -graceful-kill=true -directory="$ROOTDIR" -exclude-dir=".git" -exclude-dir=".idea" -exclude-dir=".idea"
  ;;
dev-docker-build)
  DOCKER_BUILDKIT=1 docker build --ssh default -t app $ROOTDIR
  ;;
*)
  echo "Usage: $0 [option...] {dev|build|test|docker|dev-docker}" >&2
  echo
  ;;
esac

cd $ROOTDIR
